name: Node-CI

on:
  push:
    branches: master
  pull_request:
  release:
    types: [released]

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.14.x, 18.x, 20.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build and test
        run: |
          yarn install
          yarn run build
          yarn test
        env:
          CI: true

  publish-npm:
    # publish only if we are on our own repo
    if: github.repository == 'EpicKris/compressarr' && github.event_name == 'release'

    needs: build # only run if build succeeds

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 10 # use the minimum required version
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
